name: course_manager
description: Course Manager Prototype
dependencies:
  polymer: any
  core_elements: any
  paper_elements: any
transformers:
- polymer:
    entry_points:
    - web/index.html
- $dart2js:
    minify: true
